#!/bin/bash
docker  run -i --rm --init  -v $1:/data   biodepot/alpine-bash:3.11.6__45283ff2 printenv  
docker  run -i --rm --init  -v $1:/data   biodepot/awss3create:1.16.272__python_3.8.0__alpine-3.10__70a965da create.sh /data/.aws mybucketbio us-east-2 
docker  run -i --rm --init  -v $1:/data   biodepot/awss3create:1.16.272__python_3.8.0__alpine-3.10__70a965da create.sh /data/.aws mybucketbio us-east-2 
docker  run -i --rm --init  -v $1:/data   biodepot/awss3create:1.16.272__python_3.8.0__alpine-3.10__70a965da create.sh /data/.aws mybucketbio us-east-2 
docker  run -i --rm --init  -v $1:/data  -e DIRS=[\"dtoxs/\"] -e AWS_ACCESS_KEY_ID=AKIAXJASWUXDVS5RBIAS -e AWS_SECRET_ACCESS_KEY=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 -e AWS_DEFAULT_REGION=us-east-2  biodepot/s3download:1.16.272__python_3.8.0__alpine-3.10__a6e18c85 download.sh /data/.aws biodepot-share /data/lambda_test/dtoxs 
docker  run -i --rm --init  -v $1:/data  -e awsdir=/data/.aws -e CLOUD_DIR=lambda_test/dtoxs/Aligns -e BUCKET=mybucketbio -e SPLIT_THREADS=1 -e SEQS_DIR=/data/lambda_test/dtoxs/Seqs -e OUTPUTDIR=/data/lambda_test/dtoxs/Aligns -e UPLOAD_THREADS=10 -e UPLOAD_THREADS_AFTER=16 -e NFILES=12 -e npairs=6 -e fastq_suffix=fastq.gz -e R1fastq_suffix=R1.fastq.gz -e R2fastq_suffix=R2.fastq.gz  biodepot/umisplit_awsupload:1.16.272__python_3.8.0__alpine-3.10__23ee1727 umisplit_awsupload.sh  -t 1 -b /data/lambda_test/dtoxs/References/Broad_UMI/barcodes_trugrade_96_set4.dat -o /data/lambda_test/dtoxs/Aligns -f  -s 60000 -l 16 -q 10 -m 0 -d  -N 0 
docker  run -i --rm --init  -v $1:/data  -e awsdir=/data/.aws -e CLOUD_DIR=lambda_test/dtoxs/Aligns -e BUCKET=mybucketbio -e SPLIT_THREADS=1 -e SEQS_DIR=/data/lambda_test/dtoxs/Seqs -e OUTPUTDIR=/data/lambda_test/dtoxs/Aligns -e UPLOAD_THREADS=10 -e UPLOAD_THREADS_AFTER=16 -e NFILES=12 -e npairs=6 -e fastq_suffix=fastq.gz -e R1fastq_suffix=R1.fastq.gz -e R2fastq_suffix=R2.fastq.gz  biodepot/umisplit_awsupload:1.16.272__python_3.8.0__alpine-3.10__23ee1727 umisplit_awsupload.sh  -t 1 -b /data/lambda_test/dtoxs/References/Broad_UMI/barcodes_trugrade_96_set4.dat -o /data/lambda_test/dtoxs/Aligns -f  -s 60000 -l 16 -q 10 -m 0 -d  -N 0 
docker  run -i --rm --init  -v $1:/data  -e awsdir=/data/.aws -e CLOUD_DIR=lambda_test/dtoxs/Aligns -e BUCKET=mybucketbio -e SPLIT_THREADS=1 -e SEQS_DIR=/data/lambda_test/dtoxs/Seqs -e OUTPUTDIR=/data/lambda_test/dtoxs/Aligns -e UPLOAD_THREADS=10 -e UPLOAD_THREADS_AFTER=16 -e NFILES=12 -e npairs=6 -e fastq_suffix=fastq.gz -e R1fastq_suffix=R1.fastq.gz -e R2fastq_suffix=R2.fastq.gz  biodepot/umisplit_awsupload:1.16.272__python_3.8.0__alpine-3.10__23ee1727 umisplit_awsupload.sh  -t 1 -b /data/lambda_test/dtoxs/References/Broad_UMI/barcodes_trugrade_96_set4.dat -o /data/lambda_test/dtoxs/Aligns -f  -s 60000 -l 16 -q 10 -m 0 -d  -N 0 
docker  run -i --rm --init  -v $1:/data  -e awsdir=/data/.aws -e CLOUD_DIR=lambda_test/dtoxs/Aligns -e BUCKET=mybucketbio -e SPLIT_THREADS=1 -e SEQS_DIR=/data/lambda_test/dtoxs/Seqs -e OUTPUTDIR=/data/lambda_test/dtoxs/Aligns -e UPLOAD_THREADS=10 -e UPLOAD_THREADS_AFTER=16 -e NFILES=12 -e npairs=6 -e fastq_suffix=fastq.gz -e R1fastq_suffix=R1.fastq.gz -e R2fastq_suffix=R2.fastq.gz  biodepot/umisplit_awsupload:1.16.272__python_3.8.0__alpine-3.10__23ee1727 umisplit_awsupload.sh  -t 1 -b /data/lambda_test/dtoxs/References/Broad_UMI/barcodes_trugrade_96_set4.dat -o /data/lambda_test/dtoxs/Aligns -f  -s 60000 -l 16 -q 10 -m 0 -d  -N 0 
docker  run -i --rm --init  -v $1:/data  -e awsdir=/data/.aws -e CLOUD_DIR=lambda_test/dtoxs/Aligns -e BUCKET=mybucketbio -e SPLIT_THREADS=1 -e SEQS_DIR=/data/lambda_test/dtoxs/Seqs -e OUTPUTDIR=/data/lambda_test/dtoxs/Aligns -e UPLOAD_THREADS=10 -e UPLOAD_THREADS_AFTER=16 -e NFILES=12 -e npairs=6 -e fastq_suffix=fastq.gz -e R1fastq_suffix=R1.fastq.gz -e R2fastq_suffix=R2.fastq.gz  biodepot/umisplit_awsupload:1.16.272__python_3.8.0__alpine-3.10__23ee1727 umisplit_awsupload.sh  -t 1 -b /data/lambda_test/dtoxs/References/Broad_UMI/barcodes_trugrade_96_set4.dat -o /data/lambda_test/dtoxs/Aligns -f  -s 60000 -l 16 -q 10 -m 0 -d  -N 0 
docker  run -i --rm --init  -v $1:/data  -e awsdir=/data/.aws -e CLOUD_DIR=lambda_test/dtoxs/Aligns -e BUCKET=mybucketbio -e SPLIT_THREADS=1 -e SEQS_DIR=/data/lambda_test/dtoxs/Seqs -e OUTPUTDIR=/data/lambda_test/dtoxs/Aligns -e UPLOAD_THREADS=10 -e UPLOAD_THREADS_AFTER=16 -e NFILES=12 -e npairs=6 -e fastq_suffix=fastq.gz -e R1fastq_suffix=R1.fastq.gz -e R2fastq_suffix=R2.fastq.gz  biodepot/umisplit_awsupload:1.16.272__python_3.8.0__alpine-3.10__23ee1727 umisplit_awsupload.sh  -t 1 -b /data/lambda_test/dtoxs/References/Broad_UMI/barcodes_trugrade_96_set4.dat -o /data/lambda_test/dtoxs/Aligns -f  -s 60000 -l 16 -q 10 -m 0 -d  -N 0 
docker  run -i --rm --init  -v $1:/data  -e awsdir=/data/.aws -e CLOUD_DIR=lambda_test/dtoxs/Aligns -e BUCKET=mybucketbio -e SPLIT_THREADS=1 -e SEQS_DIR=/data/lambda_test/dtoxs/Seqs -e OUTPUTDIR=/data/lambda_test/dtoxs/Aligns -e UPLOAD_THREADS=10 -e UPLOAD_THREADS_AFTER=16 -e NFILES=12 -e npairs=6 -e fastq_suffix=fastq.gz -e R1fastq_suffix=R1.fastq.gz -e R2fastq_suffix=R2.fastq.gz  biodepot/umisplit_awsupload:1.16.272__python_3.8.0__alpine-3.10__23ee1727 umisplit_awsupload.sh  -t 1 -b /data/lambda_test/dtoxs/References/Broad_UMI/barcodes_trugrade_96_set4.dat -o /data/lambda_test/dtoxs/Aligns -f  -s 60000 -l 16 -q 10 -m 0 -d  -N 0 
docker  run -i --rm --init  -v $1:/data   biodepot/deploy_lambda:1.16.272__python_3.8.0__alpine-3.10__603a9007 deploy.py  -c /data/.aws -t dtoxspubsub --fn dtestfunction --fr us-east-2 --handler main.lambda_handler -m 3008 -p dtoxspolicy --role dtoxsrole --fz /data/lambda_test/dtoxs/dtoxsfunction.zip -u dtoxsuser 
docker  run -i --rm --init  -v $1:/data   biodepot/deploy_lambda:1.16.272__python_3.8.0__alpine-3.10__603a9007 deploy.py  -c /data/.aws -t dtoxspubsub --fn dtestfunction --fr us-east-2 --handler main.lambda_handler -m 3008 -p dtoxspolicy --role dtoxsrole --fz /data/lambda_test/dtoxs/dtoxsfunction.zip -u dtoxsuser 
docker  run -i --rm --init  -v $1:/data   biodepot/deploy_lambda:1.16.272__python_3.8.0__alpine-3.10__603a9007 deploy.py  -c /data/.aws -t dtoxspubsub --fn dtestfunction --fr us-east-2 --handler main.lambda_handler -m 3008 -p dtoxspolicy --role dtoxsrole --fz /data/lambda_test/dtoxs/dtoxsfunction.zip -u dtoxsuser 
docker  run -i --rm --init  -v $1:/data   biodepot/deploy_lambda:1.16.272__python_3.8.0__alpine-3.10__603a9007 deploy.py  -c /data/.aws -t dtoxspubsub --fn dtestfunction --fr us-east-2 --handler main.lambda_handler -m 3008 -p dtoxspolicy --role dtoxsrole --fz /data/lambda_test/dtoxs/dtoxsfunction.zip -u dtoxsuser 
docker  run -i --rm --init  -v $1:/data   biodepot/deploy_lambda:1.16.272__python_3.8.0__alpine-3.10__603a9007 deploy.py  -c /data/.aws -t dtoxspubsub --fn dtestfunction --fr us-east-2 --handler main.lambda_handler -m 3008 -p dtoxspolicy --role dtoxsrole --fz /data/lambda_test/dtoxs/dtoxsfunction.zip -u dtoxsuser 
docker  run -i --rm --init  -v $1:/data   biodepot/s3upload:1.16.272__python_3.8.0__alpine-3.10__2cbb8076 upload.sh  /data/.aws /data/lambda_test/dtoxs/executables mybucketbio lambda_test/dtoxs/executables 
docker  run -i --rm --init  -v $1:/data   biodepot/s3upload:1.16.272__python_3.8.0__alpine-3.10__2cbb8076 upload.sh  /data/.aws /data/lambda_test/dtoxs/executables mybucketbio lambda_test/dtoxs/executables 
docker  run -i --rm --init  -v $1:/data   biodepot/s3upload:1.16.272__python_3.8.0__alpine-3.10__2cbb8076 upload.sh  /data/.aws /data/lambda_test/dtoxs/References/Broad_UMI mybucketbio lambda_test/dtoxs/References/Broad_UMI 
docker  run -i --rm --init  -v $1:/data   biodepot/s3upload:1.16.272__python_3.8.0__alpine-3.10__2cbb8076 upload.sh  /data/.aws /data/lambda_test/dtoxs/References/Broad_UMI mybucketbio lambda_test/dtoxs/References/Broad_UMI 
docker  run -i --rm --init  -v $1:/data  -e bwa_l=24 -e bwa_t=2  biodepot/lambda_umi_align:1.16.272__python_3.8.0__alpine-3.10__a7510339 setupAWS.py  -b mybucketbio -c /data/.aws --region us-east-2 -t dtoxspubsub -r dtoxsrecv -s dtoxsrecvsub --fn dtestfunction --fastq_suffix fq -w lambda_test/dtoxs --aligns lambda_test/dtoxs/Aligns --uploadDir saf 
docker  run -i --rm --init  -v $1:/data  -e bwa_l=24 -e bwa_t=2  biodepot/lambda_umi_align:1.16.272__python_3.8.0__alpine-3.10__a7510339 setupAWS.py  -b mybucketbio -c /data/.aws --region us-east-2 -t dtoxspubsub -r dtoxsrecv -s dtoxsrecvsub --fn dtestfunction --fastq_suffix fq -w lambda_test/dtoxs --aligns lambda_test/dtoxs/Aligns --uploadDir saf 
docker  run -i --rm --init  -v $1:/data  -e bwa_l=24 -e bwa_t=2  biodepot/lambda_umi_align:1.16.272__python_3.8.0__alpine-3.10__a7510339 setupAWS.py  -b mybucketbio -c /data/.aws --region us-east-2 -t dtoxspubsub -r dtoxsrecv -s dtoxsrecvsub --fn dtestfunction --fastq_suffix fq -w lambda_test/dtoxs --aligns lambda_test/dtoxs/Aligns --uploadDir saf 
docker  run -i --rm --init  -v $1:/data  -e bwa_l=24 -e bwa_t=2  biodepot/lambda_umi_align:1.16.272__python_3.8.0__alpine-3.10__a7510339 setupAWS.py  -b mybucketbio -c /data/.aws --region us-east-2 -t dtoxspubsub -r dtoxsrecv -s dtoxsrecvsub --fn dtestfunction --fastq_suffix fq -w lambda_test/dtoxs --aligns lambda_test/dtoxs/Aligns --uploadDir saf 
docker  run -i --rm --init  -v $1:/data  -e bwa_l=24 -e bwa_t=2  biodepot/lambda_umi_align:1.16.272__python_3.8.0__alpine-3.10__a7510339 setupAWS.py  -b mybucketbio -c /data/.aws --region us-east-2 -t dtoxspubsub -r dtoxsrecv -s dtoxsrecvsub --fn dtestfunction --fastq_suffix fq -w lambda_test/dtoxs --aligns lambda_test/dtoxs/Aligns --uploadDir saf 
docker  run -i --rm --init  -v $1:/data  -e bwa_l=24 -e bwa_t=2  biodepot/lambda_umi_align:1.16.272__python_3.8.0__alpine-3.10__a7510339 setupAWS.py  -b mybucketbio -c /data/.aws --region us-east-2 -t dtoxspubsub -r dtoxsrecv -s dtoxsrecvsub --fn dtestfunction --fastq_suffix fq -w lambda_test/dtoxs --aligns lambda_test/dtoxs/Aligns --uploadDir saf 
docker  run -i --rm --init  -v $1:/data  -e DIRS=[\"lambda_test/dtoxs/saf/*Lane1*.saf\",\"lambda_test/dtoxs/saf/*Lane2*.saf\",\"lambda_test/dtoxs/saf/*Lane3*.saf\",\"lambda_test/dtoxs/saf/*Lane4*.saf\",\"lambda_test/dtoxs/saf/*Lane5*.saf\",\"lambda_test/dtoxs/saf/*Lane6*.saf\"] -e nThreads=10  biodepot/s3download:1.16.272__python_3.8.0__alpine-3.10__a6e18c85 download.sh /data/.aws mybucketbio /data/lambda_test/dtoxs/saf 
docker  run -i --rm --init  -v $1:/data   biodepot/umimerge:ubuntu_18.04__3654016e umimerge_parallel -s /data/lambda_test/dtoxs/References/Broad_UMI/Human_RefSeq/refGene.hg19.sym2ref.dat -e /data/lambda_test/dtoxs/References/Broad_UMI/ERCC92.fa -b /data/lambda_test/dtoxs/References/Broad_UMI/barcodes_trugrade_96_set4.dat -o  /data/lambda_test/dtoxs/Counts  -f -a /data/lambda_test/dtoxs/saf -t 16 -p 0 -i RNAseq_20150409 -m  
docker  run -i --rm --init  -v $1:/data -v $1/lambda_test/dtoxs:/home/user/data   biodepot/dtoxs_analysis:1.0__ubuntu_18.04__bioc-3.7__r_3.5.1__7d8341e2 bash -c 'rm -f /home/user/data/Counts/RNAseq-Read-Counts.*  && mkdir -p /home/user/data/Results  && Rscript /home/user/Programs/Extract-Gene-Expression-Samples.R /home/user/data/Counts /home/user/Programs  && Rscript /home/user/Programs/Compare-Molecule-Expression.R /home/user/data/Configs/Configs.LINCS.Dataset.Gene.LINCS.20150409.tsv /home/user/data /home/user/Programs '
docker  run -i --rm --init -e DISPLAY=:1 -v /tmp/.X11-unix:/tmp/.X11-unix  -v $1:/data   biodepot/gnumeric:1.12.18__debian-jessie-slim__080418 gnumeric -g 500x500 /data/lambda_test/dtoxs/Results/FDR-0.1/TOP-40.tsv 
